# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: TDD - Java CI with Maven

on: # here the EVENT is/the events are defined which trigger/s the workflow
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs: # here is defined, what should be done
  build: # name of the job

    runs-on: windows-latest # GitHub supported VMs with (specific) operating systems versions

    steps: # listed with hyphens
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
        architecture: x64
        cache: maven
    - name: Build with Maven
      run: mvn -B -e -X  package --file pom.xml
      
  test:
      runs-on: windows-latest
      steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: 11
      - name: Test with Maven
        run: mvn -B package --file pom.xml test
